reactjs/ko.react.dev

.github/PULL_REQUEST_TEMPLATE.md
https://github.com/reactjs/ko.reactjs.org/issues/23
=> fix broken links in PULL_REQUEST_TEMPLATE.md

src/components/LayoutHeader/DocSearch.js, src/components/LayoutHeader/Header.js
[스페인어 번역본](https://es.reactjs.org/)을 보면 React, Languages, GitHub 빼고 번역이 허용되는 것 같습니다.
=> Translate Header text

src/pages/index.js
=> Translate some text in home page

content/warnings/special-props.md
=> Translate Special Props

content/docs/cdn-links.md
https://github.com/reactjs/ko.reactjs.org/issues/1
installation / cdn-links
=> translate cdn links

.github/PULL_REQUEST_TEMPLATE.md
This pull request adds "check best practices" step to GitHub PR template.
=> Add check best practices step to pull request template

content/tutorial/nav.yml
=> Translate tutorial navigation

src/components/LayoutHeader/DocSearch.js
=> Change DocSearch API key

src/components/LayoutHeader/DocSearch.js
=> Fix docsearch index name

content/docs/faq-internals.md
=> Translate FAQ > Virtual DOM and Internals

content/docs/create-a-new-react-app.md
=> Wrap script tag with code block

content/docs/reference-react-component.md
=> Update translated term, composition

content/docs/context.md
=> typo correct

content/docs/create-a-new-react-app.md
This is not cleaned up in #211 (i2f7631)
=> Clean up git merge conflict text

content/docs/create-a-new-react-app.md
=> Fix Typo in hooks-reference.md

content/docs/reconciliation.md
=> fix typo in reconciliation.md

content/docs/concurrent-mode-suspense.md
Note to Hacktoberfest 🎃 participants:
While we appreciate the enthusiasm, we are experiencing a high volume of drive-by pull requests (one-line changes, README tweaks, etc.). Please remember that hundreds of people are subscribed to this repo and will receive notifications for these PRs. Spam submissions will be closed and won't count towards your Hacktoberfest goals.
Please search for issues tagged [`good first issue`][gfi] or [`hacktoberfest`][hacktoberfest] to find things to work on.
You can also search [all of GitHub][all].
[gfi]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[hacktoberfest]: https://github.com/reactjs/reactjs.org/issues?q=is%3Aissue+is%3Aopen+label%3A"good+first+issue"
[all]: …
=> Fix sentences that are less translated

content/docs/reference-react-dom-server.md
=> Delete Unnecessary Characters

src/pages/versions.js
=> Translate to Korean for React Versions

content/docs/reference-javascript-environment-requirements.md
[React 공식문서](https://ko.reactjs.org/docs/javascript-environment-requirements.html)의 [JS 환경 요구사항] 페이지의 내용 중 오타를 수정하였습니다.  
<p align="center">[수정 전]</p>  
<p align="center">[수정 후]</p>  
잘못된 부분이 있다면 알려주시길 부탁드립니다.
감사합니다.
=> Remove garbled characters

content/docs/faq-ajax.md
=> updated a paragraph in Korean

content/docs/components-and-props.md
최상단의 제목
Components and Props -> Components와 Props
=> Fix title not completely translated

content/docs/conditional-rendering.md
=> Fix typo conditional-rendering.md

content/docs/getting-started.md
getting-started에서 ref문서로 가는 링크 수정했습니다.
=> Fix broken link

content/docs/state-and-lifecycle.md
누락된 문장 추가했습니다.
ko-locale: https://ko.reactjs.org/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class
en-us: https://reactjs.org/docs/state-and-lifecycle.html#adding-lifecycle-methods-to-a-class 
- AS IS 
-  또한 `Clock`에 의해 생성된 DOM이 삭제될 때마다 [타이머를 해제](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/clearInterval)하려고 합니다.
- TO BE
- 또한 `Clock`에 의해 생성된 DOM이 삭제될 때마다 [타이머를 해제](https://developer.mozilla.org/en-US/docs/Web/API/WindowTimers/clearInterval)하려고 합니다. **이것은 React에서 “언마운팅”이라고 합니다.**
원문: We also want to clear that timer whenever the DOM produced by the Clock is removed. This is called “unmounting” in React.
=> feat: 누락된 문장 추가, state-and-lifecycle.md 

content/docs/testing-recipes.md
testing-recipes에 번역이 안 된 부분을 번역했습니다.
=> translate testing-recipes

beta/src/pages/learn/start-a-new-react-project.md
`Opinionated/unopinionated framework`를 의역하여 `특화된/유연한 프레임워크`로 번역하였습니다.
---
=> Translate start a new react project

beta/src/pages/learn/extracting-state-logic-into-a-reducer.md, beta/src/sidebarLearn.json
=> Translate: 'extracting state logic into a reducer' section

content/docs/hooks-intro.md
=> Correct a typo

beta/src/pages/learn/referencing-values-with-refs.md, beta/src/sidebarLearn.json
=> Referencing Values with Refs 번역

content/docs/faq-functions.md
공식 문서를 읽던 중 단순 오타를 발견해 수정하였습니다
=> faq-functions 오타 수정

beta/src/pages/learn/importing-and-exporting-components.md
=> Translate importing and exporting components

content/docs/components-and-props.md, content/docs/hello-world.md, content/docs/introducing-jsx.md, content/docs/rendering-elements.md
…and-props
문서를 읽다 깨진 부분을 발견해서 수정했습니다.
=> hello-world, introduction-jsx, rendering-elements, components-and-props 문서 수정.

content/docs/code-splitting.md
=> Remove Conflict Code in code-splitting.md

content/tutorial/tutorial.md
[Tutorial](https://github.com/reactjs/ko.reactjs.org/blob/main/content/tutorial/tutorial.md)에서 새롭게 추가된 문단을 번역해보았습니다.
=> docs: Translate new sentence in tutorial

content/docs/reference-react-component.md
=> Remove original english text remains

README.md
=> fix: conflict readme.md

beta/src/pages/learn/your-first-component.md
=> Translate document to korean (Your first component)

content/versions.yml, src/site-constants.js
React 18 버전이 출시됨으로써 한국어 문서에도 해당 변경 로그를 추가하였습니다.
데스크탑
모바일
=> Add React 18 version change log

content/docs/code-splitting.md
Promise의 resolve가  '결정'으로 해석되어 있어 '이행'으로 변경하였습니다.
또한, 의미에 맞게 번역을 수정하였습니다.
=> Fix lazy 함수 인자 설명 변경

beta/package.json, beta/src/components/MDX/MDXComponents.tsx, beta/src/pages/learn/thinking-in-react.md, beta/src/pages/learn/updating-arrays-in-state.md, beta/yarn.lock, content/docs/jsx-in-depth.md, content/warnings/unknown-prop.md
[해당 commit](https://github.com/reactjs/ko.reactjs.org/commit/c5c3c53dcfefaca865da41be4162c184278b3dba)의 conflict data를 제거했습니다
=> Remove conflict data

content/docs/jsx-in-depth.md
제대로 merge가 되지 않아 페이지가 깨지는 문제를 해결했습니다. 첫 기여입니다 나이스!!
=> Fix sparead-attribute contents description

content/tutorial/tutorial.md
[#4461](https://github.com/reactjs/reactjs.org/pull/4461)에서 새롭게 변경된 문단을 번역해보았습니다.
추가로 번역 중 오탈자를 찾아 수정하였습니다. (`해아합니다.` -> `해야 합니다.`)
=> docs: Translate sentences in the tutorial

content/docs/error-decoder.md
=> Translate Error Decoder

content/docs/forwarding-refs.md
오른쪽 목차의 제목 -> Ref 전달하기
페이지 타이틀 ->  Forwarding Refs
마이너 하지만 누락된 부분인듯하여 PR올려봅니다!
=> 제목 수정(오른쪽 목차의 제목과 페이지 제목이 맞지 않음)

content/docs/create-a-new-react-app.md
=> create-a-new-react-app: 문맥을 매끄럽게 수정

content/docs/reference-react-dom.md
hydrate() 파트 부분의 note가 번역되어 있지 않아 업데이트 했습니다.
=> update hydrate() note 

README.md
위키 안에 있는 번역 가이드를 README 로 일단 옮겨옵니다 ㅎㅎ
=> README 에 한국어 번역 가이드 추가

examples/forwarding-refs/fancy-button-simple-ref.js
=> fix: 오타 수정(작접 -> 직접)

README.md
기존에 있던 README 번역된것을 가져와 새로 적용해봅니다
=> fix: Readme 번역

.github/ISSUE_TEMPLATE/term.md
용어 번역에 대한 원활한 논의가 이루어지도록 이슈 템플릿을 추가합니다. 템플릿은 제가 임의로 제안해보았는데, 여러사람들이 논의에 참여할 수 있도록 템플릿에 대한 제안을 해주시면 좋을것 같습니다.
=> Update issue templates to discuss terms

src/content/learn/writing-markup-with-jsx.md
=> Translate: Writing Markup with JSX

src/content/reference/react/createRef.md
=> Translate: creatRef

src/content/reference/react/useCallback.md
Reverts reactjs/ko.react.dev#612
=> Revert "Translate : useCallback"

src/content/learn/manipulating-the-dom-with-refs.md
=> Translate: manipulating the dom with refs

src/content/reference/react/index.md
=> Translate: Hooks

src/content/blog/2021/12/17/react-conf-2021-recap.md
=> Translate: React Conf 2021 Recap

src/content/blog/2020/12/21/data-fetching-with-react-server-components.md
=> Translate: blog - ntroducing Zero-Bundle-Size React Server Components

src/sidebarLearn.json
사이드바의 오타로 인해 잘못된 경로로 이동하는 문제가 있어 이를 수정하였습니다.
=> Fix typo in sidebar

src/components/Layout/HomeContent.js
```diff
- Next.js 또는Remix
+ Next.js 또는 Remix
```
- before
- after
=> docs: home에서 띄어쓰기 개선

src/content/learn/sharing-state-between-components.md
#398 이후 정식버전에서 추가로 반영된 영역에 대해 번역 추가했습니다.
=> Translate: sharing-state-between-components

src/content/blog/2022/03/29/react-v18.md, src/content/blog/index.md
| as-is | to-be |
|:---:|:---:|
|<img width="959" alt="as-is-v18" src="https://github.com/reactjs/ko.react.dev/assets/69497936/a237aca1-63e0-4c98-8122-4ac20e8167ba">  | <img width="959" alt="to-be-v18" src="https://github.com/reactjs/ko.react.dev/assets/69497936/7394e2c1-08c8-4eab-b510-74ffb2127402"> |
=> Translate: react-v18 (Blog post)

src/content/blog/2021/06/08/the-plan-for-react-18.md
=> docs: Translate the-plan-for-react-18

src/content/learn/sharing-state-between-components.md
=> Translate: sharing state between components

src/content/reference/react/StrictMode.md
=> Translate: StrictMode

src/content/reference/react/Children.md
=> Translate: Legacy API - Children

src/content/reference/react/useState.md
=> translate: useState

src/content/learn/importing-and-exporting-components.md
=> Translate: Importing and Exporting Components

src/content/learn/referencing-values-with-refs.md
=> Translate: referencing values with refs

src/content/reference/react-dom/server/index.md
=> Translate: Server React DOM APIs

src/content/reference/react-dom/flushSync.md
=> Translate: flushSync

src/content/reference/react/createContext.md
=> Translate : createContext

src/content/community/videos.md
=> Translate: React Videos

src/content/community/docs-contributors.md
=> Translate: docs contributors

src/content/reference/react-dom/server/renderToPipeableStream.md
https://github.com/reactjs/ko.react.dev/issues/705
요기에서 나온 이슈를 해결합니다
=> fix: 서스펜스 -> Suspense

src/content/community/acknowledgements.md
=> Translate: Acknowledgements

src/content/blog/index.md
=> Translate: sync blog index

src/content/learn/lifecycle-of-reactive-effects.md
=> Translate: Lifecycle of Reactive Effects

src/content/reference/react/use.md
=> Translate: use 번역

src/content/reference/react/useMemo.md
=> docs: useMemo 번역

src/content/reference/react/useLayoutEffect.md
=> Translate: useLayoutEffect

src/pages/404.js, src/pages/500.js
에러 페이지에 대한 번역이 이슈로써 관리되고 있지 않지만 아직 번역이 되지 않았고, 번역이 되면 좋을 것 같아 번역 후 PR을 작성합니다.
번역에 대해서 추가 의견 주신다면 반영하도록 하겠습니다!
=> Translate: error page (404, 500)

src/content/reference/react/use-server.md
업데이트 된 내용에 대하여 추가 번역 작업을 진행했습니다.
- https://github.com/reactjs/ko.react.dev/issues/811#issuecomment-1879830322
=> translate: use-server

src/content/reference/react-dom/client/hydrateRoot.md, src/content/reference/react-dom/render.md, src/content/reference/react-dom/server/renderToReadableStream.md, src/content/reference/react-dom/server/renderToStaticMarkup.md, src/content/reference/react-dom/server/renderToStaticNodeStream.md, src/content/reference/react/Fragment.md, src/content/reference/react/cache.md, src/content/reference/react/createContext.md, src/content/reference/react/createRef.md, src/content/reference/react/startTransition.md, src/content/reference/react/use.md
- 번역된 문서 중 Reference 그대로 쓰이거나 참조로 번역된 부분을 레퍼런스로 수정
=> fix: 오타 수정

src/content/learn/updating-arrays-in-state.md
=> fix: 참조 링크 수정

src/content/reference/react-dom/hooks/useFormStatus.md
=> Translate: useFormStatus

src/content/reference/react-dom/hooks/useFormState.md
=> Translate: useFormState 

src/content/reference/react-dom/components/common.md
=> fix: add missing translation

src/content/learn/referencing-values-with-refs.md, src/content/learn/removing-effect-dependencies.md, src/content/learn/synchronizing-with-effects.md, src/content/learn/writing-markup-with-jsx.md
안녕하세요.
문서 내 오타 및 링크 경로 수정하였습니다.
=> fix: 오타 및 링크수정

src/content/reference/react-dom/hooks/index.md
안녕하세요 레퍼런스 탭에 있는 react-dom의 hooks 페이지를 번역했습니다.
=> Translate reference hooks

src/content/reference/react/useEffect.md
- /reference/react/useEffect의 코드 주석들을 번역했습니다.
=> translate: Code comments for useEffect

src/content/learn/describing-the-ui.md
안녕하세요 문서의 https://ko.react.dev/learn/describing-the-ui#your-ui-as-a-tree 부분의 번역이 누락되어서 해당 부분을 번역했습니다.
=> Translate your UI as a tree

src/content/learn/updating-objects-in-state.md
- /learn/updating-objects-in-state의 Deep Dive 제목들을 번역했습니다.
=> translate: Translated Deep Dive titles in updating-objects-in-state

src/content/learn/lifecycle-of-reactive-effects.md
=> fix: error in translation

src/content/versions.md
안녕하세요. react versions 페이지, #916 을 번역하였습니다.
=> Translate react versions

src/content/reference/react/useSyncExternalStore.md
=> Translate: useSyncExternalStore

src/content/reference/rsc/server-actions.md
=> Translate: Server Actions

src/content/reference/react-dom/components/link.md
#931 
[link 컴포넌트 페이지](https://ko.react.dev/reference/react-dom/components/link) 번역 완료했습니다.
=> Translate: link

src/content/reference/rules/components-and-hooks-must-be-pure.md
=> Translate: Components and Hooks must be pure

src/content/learn/react-compiler.md, src/sidebarLearn.json
=> Translate: React Compiler

husky.config.js, lint-staged.config.js
안녕하세요😊 중복 설정되어 있는 `husky.config.js`와 `lint-staged.config.js` 파일을 삭제하였습니다.
설정(config) 파일 삭제 후에도 pre-commit hook 및 lint-staged는 정상 작동합니다!
삭제 이유는 아래와 같습니다.
1. `husky.config.js`
- 해당 파일에 존재하는 `'pre-commit': 'lint-staged'`의 내용은 이미 [`.husky/pre-commit`](https://github.com/reactjs/ko.react.dev/blob/c5e9effb61466b615909ddb158a98e5de24d6da2/.husky/pre-commit#L4)에 존재하는 내용입니다. 즉, 중복된 내용을 다시 설정하고 있습니다.
- 영어 원문 리포지토리인 [react.dev](https://github.com/reactjs/react.dev)에서는 해당 파일을 사용하고 있지 않습니다.
1. `lint-staged.config.js`
- 해당 파일은 textlint관련 legacy 파일입니다.
- [`package.json`](https://github.com/reactjs/ko.react.dev/blob/c5e9effb61466b615909ddb158a98e5de24d6da2/package.json#L116-L119) 내부의 `lint-staged`와 중복됩니다.
- 앞으로, `husky` 및 `lint-staged`를 이용한 textlint 자동 검사 기능은 `package.json` 내부의 `lint-staged` 영역에 추가할 …
=> remove:  `husky.config.js` and `lint-staged.config.js`

src/content/blog/index.md
=> Sync blogcard title

textlint/data/rules/translateGlossary.js, textlint/generators/genTranslateGlossaryDocs.js, wiki/translate-glossary.md
안녕하세요😊
지난번에 추가한 용어들을 대상으로 `textlint-test` 명령어(테스트 명령어)를 실행하였을 때 오류가 발생하여, 해당 부분 수정ㆍ보완하여 PR 올립니다😭
이어서 github actions 및 husky, lint-staged에 `textlint-test` 추가하여 PR 올리겠습니다.
```text
1) translateGlossary
term: Spec, Specification
한글이 포함된 Str node. Spec, Specification 가나다 abc.:
AssertionError [ERR_ASSERTION]: "message should be "'Spec, Specification'은/는 '명세'(으)로 번역되어야 합니다."
+ expected - actual
-'Spec'은/는 '명세'(으)로 번역되어야 합니다.
+'Spec, Specification'은/는 '명세'(으)로 번역되어야 합니다.
at D:\Cloud_Git\ko.react.dev\node_modules\textlint-tester\lib\src\test-util.js:116:24
at Array.forEach (<anonymous>)
at D:\Cloud_Git\ko.react.dev\node_modules\textlint-tester\lib\src\test-util.js:98:16
2) translateGlossary
term: Returns(제목에 사용된 경우)
한글이 포함된 Str node. Returns(제목에 사용된 경우) 가나다 abc.:
AssertionError [ERR_ASSERTION]: …
```
=> feat: introduction of `note` key value in TranslateGlossary

package.json
안녕하세요😊 `husky`와 `lint-staged`를 이용한 textlint 테스트 자동화를 진행하였습니다.
수정 내역은 아래와 같습니다.
1. `textlint` 디렉토리 내부의 `.js` 파일이 수정된 경우에만 `yarn textlint-test`가 동작하도록 설정하였습니다.
- 해당 디렉토리 내부의 `.js` 파일들은 서로 유기적인 관계를 맺고 있어, 이 중 하나의 파일이 수정된 경우 테스트를 진행해야 합니다.
=> ci: textlint test automation using husky and lint-staged

src/content/learn/add-react-to-an-existing-project.md
안녕하세요😊 `add-react-to-an-existing-project.md` 문서 내부 링크에 오탈자가 있어 수정하였습니다.
`요` 라는 불필요한 한글이 링크에 포함되어 있어, 잘못된 링크로 이동합니다.
(요즘 프로젝트 때문에 작업이 좀 늦어지고 있습니다🙇‍♂️😭 금방 다시 돌아오겠습니다...!)
=> fix: typo in add-react-to-an-existing-project.md

src/content/learn/describing-the-ui.md
- `describing-the-ui.md` 파일의 번역되지 않은 부분을 수정하였습니다.
=> docs: update `describing-the-ui.md`

.github/PULL_REQUEST_TEMPLATE.md, README.md
안녕하세요😊
아래와 같이 부산대 맞춤법 검사기의 링크가 변경되어 `README` 및 관련 문서를 업데이트 합니다.
=> docs: update spelling check link in README.md

src/sidebarLearn.json, src/sidebarReference.json
안녕하세요😊 
사이드바에 번역 안되어 있는 일부분 소소하게 수정해보았습니다.
=> docs(translation): update sidebar

src/components/Layout/Feedback.tsx
안녕하세요😊
화면 좌측 하단에 종종 나오는 피드백 관련 UI가 애매하게 줄 바꿈이 되어 있는게 신경쓰여 수정하였습니다.
여러 사이즈의 반응형에서도 동일하게 잘 나오는 것을 확인하였습니다.
- 수정 전
- 수정 후
=> design: ux improvement in feedback.tsx

src/content/learn/passing-data-deeply-with-context.md
안녕하세요😊
`passing-data-deeply-with-context.md` 문서를 읽다가 맞춤법, 가독성이 떨어지는 문장, 번역이 잘못된 부분 등을 **영어 원문 기준**으로 수정하였습니다.
=> docs: update `passing-data-deeply-with-context.md`

src/content/reference/react-dom/components/script.md
안녕하세요😊
`script.md` 문서를 읽다가 맞춤법, 가독성이 떨어지는 문장, 번역이 잘못된 부분 등을 **영어 원문 기준**으로 수정하였습니다.
=> docs: update `script.md`

src/content/reference/react/useEffect.md
=> docs: update `useEffect.md` (#1097)

src/content/reference/react/use.md
안녕하세요!
`use.md` 를 읽어보다 어색한 문장이 있어서 수정했습니다.
=> docs: fix typo in use.md

src/content/reference/react/useActionState.md
- 어색한 번역 수정
- 코드 스타일 통일
- Server Action -> Server Function으로 React에서 네이밍을 수정함에 따라 적용 [관련 문서](https://react.dev/reference/rsc/server-functions)
=> docs: update `useActionState.md`

src/content/reference/react/useDeferredValue.md
https://github.com/reactjs/ko.react.dev/issues/1121
[useDeferredValue 페이지](https://ko.react.dev/reference/react/useDeferredValue)의 `매개변수` 및 `주의 사항` 섹션에서 새롭게 추가된 내용을 번역했습니다.
=> docs: update useDeferredValue.md

src/content/reference/react/Suspense.md
잘못된 번역 내용을 수정했어요.
`client-only-content`: `서버` 전용 콘텐츠 -> `클라이언트` 전용 콘텐츠
=> docs: fix typo in `Suspense.md`

src/content/reference/react/useTransition.md
- #1127 
- 번역되지 않은 부분 번역
- 영어와 한글로 같이 작성된 부분은 원문(영어 문서)을 참고하여 최신 내용으로 적용하며 번역
=> docs: update useTransition.md

src/content/reference/react/useTransition.md
아래 그림처럼 공식 문서에 없는 내용이 번역본에 포함되어 있어 삭제했습니다.
=> docs: remove unofficial content in useTransition.md

.github/ISSUE_TEMPLATE/need-translation.md
close #1143 
- Add `번역 필요` issue template
- `need translation` label and `[번역 필요]: `title prefix
=> docs: add need translation issue template

src/content/learn/build-a-react-app-from-scratch.md
다음 페이지를 번역했습니다.
[처음부터 React 앱 만들기](https://ko.react.dev/learn/build-a-react-app-from-scratch)
=> docs: update content/learn/build-a-react-app-from-scratch.md

src/content/learn/installation.md
다음 페이지를 번역했습니다.
[처음부터 React 앱 만들기](https://ko.react.dev/learn/installation)
=> docs: update content/learn/installation.md

src/content/learn/add-react-to-an-existing-project.md
안녕하세요! 배포 이후 확인해보다 다른 url은 suggestion 주신 url이 맞으나, github url은 vite가 아닌 vitejs라 기존 url로 이동하면 Page not found가 나오는 버그를 수정했습니다!
=> fix: update url content/learn/add-react-to-an-existing-project

src/content/learn/state-as-a-snapshot.md
현재 너비 기준 948px 이하일 때, 개행으로 인해 가독성이 떨어지는 문제가 있어 이를 수정했습니다.
=> docs: update newline learn/state-as-a-snapshot.md

src/content/reference/rsc/server-components.md
- 서버 컴포넌트 문서에서 번역문과 중복되는 원문을 제거했습니다.
- 아래 문장에서 동작하지 않는 링크에 대해서 원본 문서에서도 사용되지 않는 링크로 확인되어 제거 조치했습니다.
- 혹시 이 조치에 대해 잘못된 점이 있다면 알려주시면 감사하겠습니다.
https://github.com/reactjs/ko.react.dev/blob/f9788af3b2cbdca890adacf2b690280918dddf40/src/content/reference/rsc/server-components.md?plain=1#L302
=> docs: remove original text in server-components.md

src/content/reference/react-dom/index.md
close #1243 
https://ko.react.dev/reference/react-dom 해당 페이지에서, 
Resource Preloading APIs section을 번역하였습니다.
=> docs: translate resource-preloading-apis

src/content/learn/react-developer-tools.md
#1215
React 개발자 도구 페이지 내 Mobile (React Native) 섹션에 대한 번역을 진행했습니다.
- 원문 링크: [https://ko.react.dev/learn/react-developer-tools#mobile-react-native](https://ko.react.dev/learn/react-developer-tools#mobile-react-native)
- 관련 이슈: [https://github.com/reactjs/ko.react.dev/issues/1215](https://github.com/reactjs/ko.react.dev/issues/1215)
=> docs: add Korean translation for 'Mobile (React Native)' section

src/content/blog/2024/12/05/react-19.md, src/sidebarBlog.json
[블로그](https://ko.react.dev/blog) > [Reacv v19](https://ko.react.dev/blog/2024/12/05/react-19)의 누락된 번역을 수정하였습니다.
closed #1262
=> docs: add missing translations in `blog/react-19.md`

src/content/learn/creating-a-react-app.md
"새로운 React 앱 만들기" 페이지의 "React 팀의 풀스택 아키텍처 비전을 구성하는 기능은 무엇인가요? " 코드 예시 주석에서 한국어 맞춤법 오타를 수정했습니다. (https://github.com/reactjs/ko.react.dev/issues/1304)
=> docs: fix typo in creating-a-react-app

src/content/reference/react-dom/components/form.md
form의 참고 문서를 적절한 url로 수정하였습니다.
해당 부분 클릭시 정상적으로 작동함을 확인했습니다!
=> docs: fix wrong link of form document

src/content/community/translations.md
`/community/translations` 페이지를 영문에서 한국어로 번역했습니다.
- **파일**: `src/content/community/translations.md`
- **번역 내용**:
- 제목: "Translations" → "번역"
- 모든 섹션 내용을 한국어로 번역
- 공통 스타일 가이드 및 용어집 적용
- **유지 사항**:
- 제목 아이디 (`{/*main-site*/}`, `{/*full-translations*/}` 등) 원본 유지
- 외부 링크 URL 원본 유지
- 코드 블록 및 주석 원본 유지
=> docs: Translated translations page

src/content/community/conferences.md, src/content/community/meetups.md, src/content/community/team.md
Community 섹션의 나머지 페이지들을 영문에서 한국어로 번역하고 번역 품질을 개선했습니다.
- **team.md**: 
- React Core 섹션 설명 번역
- 피동형 문장 제거 및 문체 개선
- **meetups.md**: 
- 제목: "React Meetups" → "React 모임"
- 인트로 텍스트 번역
- **conferences.md**: 
- 제목: "React Conferences" → "React 컨퍼런스"
- 인트로 텍스트 번역
- 번역 모범 사례 적용
- 공통 스타일 가이드 및 용어집 일관성 적용
=> docs: Translate community pages to Korean
