content/home/examples/a-component-using-external-plugins.md, content/home/examples/a-simple-component.md, content/home/examples/a-stateful-component.md, content/home/examples/an-application.md, content/home/marketing/component-based.md, content/home/marketing/declarative.md, content/home/marketing/learn-once-write-anywhere.md
Please review and give me your feedback. 🙇
References:
- https://reactjs-org-ko.netlify.com/
- https://reactjs-kr.firebaseapp.com/
- https://github.com/reactjs/ja.reactjs.org/pull/55
=> Translate Home Page

.github/PULL_REQUEST_TEMPLATE.md
I made a PR for the part you suggested. Please let me know if you have an opinion.(#23)
=> Update Pull Request Templates

.circleci/config.yml, .textlintrc.js, husky.config.js, lint-staged.config.js, package.json, textlint/README.md, textlint/rules/no-endline-colon.js, textlint/rules/terminology.js, textlint/tests/no-endline-colon.spec.js, textlint/tests/terminology.spec.js, yarn.lock
This pull request adds textlint in the translation process. As a linter for text and markdown, we can use this for reducing formatting review and eventually can focus on the translation quality itself.
[`textlint/README.md`](https://github.com/reactjs/ko.reactjs.org/blob/6821f250135ed9e77257277213ae22c74f21deaa/textlint/README.md) explains an overview of how we use textlint and how to do maintenance. For proof of improvement, I implement two textlint rules (`no-endline-colon`, `terminology`)
You can see the rule implementation test status in [CircleCI "Test Textlint" step](https://circleci.com/gh/reactjs/ko.reactjs.org/120). 
Textlint is already used in [Japanese](https://github.com/reactjs/ja.reactjs.org/blob/master/textlint/jp-reactjs-org-lint.js)
=> Add textlint to improve the translation process

content/blog/2018-11-27-react-16-roadmap.md, content/blog/2019-02-06-react-v16.8.0.md, content/docs/hooks-intro.md, content/docs/hooks-overview.md, content/docs/hooks-reference.md, content/docs/nav.yml
Please review and give me your feedback. 🙇
=> Translate Hooks at a Glance

content/warnings/legacy-factories.md
=> Translate Legacy Factories

content/docs/reference-glossary.md
=> Fixed miss word on glossary

content/warnings/invalid-hook-call-warning.md
=> Translate Invalid Hook Call Warning

content/docs/web-components.md
=> Translate Web Components

content/docs/reference-test-renderer.md
=> Translate Test renderer

content/docs/rendering-elements.md
I have translated the [Rendering Elements](https://github.com/reactjs/ko.reactjs.org/blob/master/content/docs/rendering-elements.md) section.
Please let me know if you find any mistakes.
- Reference
https://www.gaesignerblog.com/post/17
https://reactjs-org-ko.netlify.com/docs/rendering-elements.html
=> Translate rendering elements

content/warnings/invalid-aria-prop.md
=> Translate Invalid Aria Prop

content/warnings/dont-call-proptypes.md
=> Translate dont-call-proptypes

content/community/conferences.md, content/docs/hooks-rules.md, content/docs/nav.yml, content/warnings/special-props.md
=> Translate Rules of Hooks

content/docs/uncontrolled-components.md
=> Translate Uncontrolled Components

content/docs/hooks-reference.md
=> Translate HOOKS > Hooks API Reference

content/warnings/unknown-prop.md
=> Translate unknown-prop

content/docs/state-and-lifecycle.md
=> Translate state-and -lifecycle

content/tutorial/tutorial.md
튜토리얼 번역에 있던 오타와 문맥상 맞지 않던 자잘한 문장 두개를 수정 했습니다.
=> Fix typo and naturally in context.

content/docs/create-a-new-react-app.md
=> Fix typo in create-a-new-react-app section

content/docs/hello-world.md
=> Fix typo in 'Hello World' page

content/docs/hooks-intro.md
=> Fix broken hyperlink in hooks-intro docs

content/docs/concurrent-mode-suspense.md
=> Translation for Suspense for Data Fetching

content/docs/concurrent-mode-suspense.md
https://ko.reactjs.org/docs/concurrent-mode-suspense.html
위 링크의 문서를 읽다가 원문 언어가 중복되는 이슈를 확인하여 중복되는 부분을 삭제했습니다.
=> Remove duplicated other language contents (content/docs/concurrent-mode-suspense)

content/docs/hooks-reference.md
=> Fix broken url in 'docs/hooks-reference'

content/docs/handling-events.md
>  React 이벤트는 브라우저 고유 이벤트와 정확히 동일하게 동작하지는 않습니다. **React events do not work exactly the same as native events.** 더 자세한 사항은 합성 이벤트을 참고하시기 바랍니다.
번역 완료된 부분  _'React events do not work exactly the same as native events'_ 이 원문에 포함되어있어 해당 부분을 삭제하였습니다.
=> docs: fix typo in handling-events.md

content/docs/reference-react.md
React.memo() 설명에 영어로 된 설명이 중복되어 영어 부분을 삭제하고 한글 부분에 원문과 같이 useState, useContext에 대한 링크를 추가했습니다 😊
- remove duplicate english content
- add link(useState/ useContext) to korean content
=> Remove duplicate content and add link

content/docs/web-components.md
=> Update web-components.md due to translation errors

content/docs/optimizing-performance.md
Change the translation naturally.
I understand the meaning of the current translation, but the flow of the sentences is not natural.
안녕하세요!
> 이는 불가피했습니다. 
`불가피하다`는 물러설곳없거나 어쩔수없다는 의미를 내포하고있습니다. 필연적이다 라는 표현이 더 명확해서 PR드렸습니다.
=> fix: change the translation naturally

content/docs/testing-recipes.md
- Fix typo `[React Testing Library] (https://testing-library.com/react)` => `[React Testing Library](https://testing-library.com/react)`
- https://ko.reactjs.org/docs/testing-recipes.html#act
=> [Fix] Typo in testing-recipes

content/docs/conditional-rendering.md
(1) skip it. 문장이 생략되어서 추가했습니다.
- 원문
- If it is false, React will ignore and skip it.
- AS IS
- 따라서 `&&` 뒤의 엘리먼트는 조건이 `true`일때 출력이 됩니다. 조건이 `false`라면 React는 무시합니다.
- TO BE
- 따라서 `&&` 뒤의 엘리먼트는 조건이 `true`일때 출력이 됩니다. 조건이 `false`라면 React는 **무시하고 건너뜁니다.**
---
(2) 기존 `false로 평가될 수 있는 표현식을 반환`가 가독성이 떨어집니다. 이에 2가지 대안을 제안합니다. 또한, 누락된 still 추가했습니다.
1. 원문의 `falsy expression`에서 `falsy` 단어 표현 사용.
2. `false로 평가될 수 있는 표현식을 반환`을 `거짓으로 평가될 수 있는 표현식을 반환`으로 수정.
- 원문
- Note that returning a falsy expression will still cause the element after && to be skipped but will return the falsy expression.
- AS IS
- false로 평가될 수 있는 표현식을 반환하면 `&&` 뒤에 있는 표현식은 건너뛰지만 false로 평가될 수 있는 표현식이 반환된다는 것에 주의해주세요.
- TO BE
- **falsy** 표현식을 반환하면 **여전히** `&&` 뒤에 있는 표현식은 건너뛰지만 **falsy** 표현식이 반환된다는 것에 주의해주세요.
=> 단어 수정 및 누락된 문장, 단어 추가 ,Conditional Rendering

content/docs/reference-react-component.md
- english version
```
getSnapshotBeforeUpdate() is invoked right before the most recently rendered output is committed to e.g. the DOM
```
- korean version
```
getSnapshotBeforeUpdate()는 가장 마지막으로 렌더링된 결과가 DOM 등에 반영되었을 때에 호출됩니다.
```
`반영되었을 때에` -> `반영되기 전에` 로 수정하였습니다.
=> fix: translation

beta/src/pages/learn/javascript-in-jsx-with-curly-braces.md, beta/src/sidebarLearn.json
=> Translate document to korean (Javascript in jsx with curly braces)

content/docs/cross-origin-errors.md
처음으로 번역 작업 참여해보는데요. 부족한점이 많이 있을거 같은데, origin 관련해서 원본 그대로 둘지 아니면 직역을 할지 등등 피드백 부탁드립니다
=> cross-origin-errors kr translate

beta/src/components/Layout/MarkdownPage.tsx, beta/src/components/Layout/Toc.tsx, beta/src/components/MDX/Challenges/Challenges.tsx, beta/src/components/MDX/ExpandableCallout.tsx, beta/src/components/MDX/ExpandableExample.tsx, beta/src/components/MDX/MDXComponents.tsx, beta/src/components/MDX/Recap.tsx, beta/src/components/MDX/Sandpack/CustomPreset.tsx, beta/src/components/MDX/YouWillLearnCard.tsx, beta/src/components/Tag.tsx
페이지를 그릴때 사용하는 컴포넌트에 있는 영문 텍스트들을 한국어로 번역 진행했습니다.
약간 어색한 부분도 있는 듯해 리뷰를 좀 받고 추가적으로 반영하는게 좋을 것 같습니다.
> Related issue #378
=> Translate component text to korean

beta/src/pages/learn/manipulating-the-dom-with-refs.md
=> Translate: manipulating-the-dom-with-refs

beta/src/pages/learn/sharing-state-between-components.md
=> Sharing state between components 번역

content/docs/hooks-faq.md
Hooks FAQ 질문 중 function이 '함수 컴포넌트'로 번역이 돼있어서 해당 질문 답변 내 '함수 컴포넌트'를 '함수'로 수정했습니다.
- english 
Is it safe to omit **functions** from the list of dependencies?
- korean 수정 전
종속성 목록에서 **함수 컴포넌트**를 생략하는 것이 안전합니까?
- korean 수정 후
종속성 목록에서 **함수**를 생략하는 것이 안전합니까?
+) 해당 질문의 dependency list가 '종속성 목록'으로 번역돼있는데 번역의 통일성을 위해 '의존성 배열'로 수정하는 것이 좋아 보입니다.
감사합니다.
=> Fix - 'function'  translation

content/docs/reference-test-renderer.md
=> Fix typo: `trestRenderer` to `TestRenderer`

content/docs/hooks-faq.md
' A miss B'는 A가 B를 놓치다로도 해석될 수 있지만  이 상황에서는 A가 B를 그리워  하다로 해석하는 것이 더 의미상으로 적절하고 전달이 잘됩니다.  state merging에 대한 설명 중 'A miss B'의 번역을 A가 B를 그리워하다로 번역을 바꾸었습니다.
=> fix: Hooks FAQ 문서 'miss' 단어 번역 변경 

content/tutorial/tutorial.md
=> fix: Add missing backticks

content/docs/hooks-reference.md
=> Fix typo in "hooks reference" document

content/docs/code-splitting.md
코드 분할 관련 내용을 읽다가 해당 내용에서 babel 관련된 deprecated된 패키지를 사용하는 문장이 있어 해당 패키지 이름과, url을 수정하였습니다. (공식 문서에서는 업데이트 되어 있더라구요)
deprecated된 패키지: https://github.com/webpack-contrib/babel-minify-webpack-plugin
혹시 더 좋은 커밋명이 있다면, 추천해주시면 감사하겠습니다. 🙇
=> 코드 분할 문서 내용 수정

content/docs/refs-and-the-dom.md
안녕하세요.
**Ref와 DOM** [페이지](https://ko.reactjs.org/docs/refs-and-the-dom.html)에서 잘못된 오탈자를 교정하여 PR을 올립니다.
- 오탈자 교정
- 마침표 위치 교정
- [한글 페이지](https://ko.reactjs.org/docs/refs-and-the-dom.html)
- [영문 페이지](https://reactjs.org/docs/refs-and-the-dom.html)
감사합니다. 🙏
=> Fix typo in Refs and the DOM

content/community/conferences.md, content/docs/hooks-faq.md, content/docs/reference-react.md
알 수 없는 문자가 포함되어 수정하였습니다.
| title | before | after |
| --- | --- | --- |
| Hook | ![image](https://user-images.githubusercontent.com/63892989/180902535-b8b105f4-58d7-4ff0-8cec-b68bb2dc7be5.png) | ![image](https://user-images.githubusercontent.com/63892989/180902560-fbbda88e-5037-432c-8c32-2479903079d2.png) |
| Children | ![image](https://user-images.githubusercontent.com/63892989/180902580-0226406d-23cc-409b-9e67-748f132b498c.png) | ![image](https://user-images.githubusercontent.com/63892989/180902603-f22efa7b-b72c-444f-b4a4-437a3290657b.png) |
| Suspense | ![image](https://user-images.githubusercontent.com/63892989/180902627-ce34b303-4dfd-4427-9d9a-e46b2dfb9192.png) | ![image](https://user-images.githubusercontent.com/63892989/180902642-b6da5e0b-ead8-4494-877d-75eb2e76ccb1.png) |
> ps. …
=> fix: 알 수 없는 문자 제거

content/docs/rendering-elements.md
To render a React element, first pass the DOM element to ReactDOM.createRoot(), then pass the React element to root.render(): 
-> React 엘리먼트를 렌더링 하기 위해서는 우선 DOM 엘리먼트를 ReactDOM.createRoot()에 전달한 다음, React 엘리먼트를 root.render()에 전달해야 합니다.
=> Translated a sentence into Korean

content/docs/higher-order-components.md, content/docs/implementation-notes.md, content/docs/jsx-in-depth.md, content/docs/typechecking-with-proptypes.md
용어 통일을 위해 맞춤법에 맞지 않는 단어가 확인되어 수정했습니다🙂
랜더 -> 렌더
=> 용어 규칙에 맞는 맞춤법으로 수정

src/components/LayoutHeader/HeaderLink.js
Fix wrapped Korean text of HeaderLink  component inside navigation bar of [reactjs offical website](https://ko.reactjs.org/)
- style `whitespace` to be `nowrap`
Below is the before & after picture
리액트 공식 문서를 모바일에서 보면 헤더의 텍스트 줄 바꿈 현상이 생겨나 style 수정하였습니다.
아래는 전후 비교 사진입니다.
|  **BEFORE** |  **AFTER**  |
|---|---|
|  <img src="https://user-images.githubusercontent.com/13115713/197377593-1b564a94-317c-4f81-81df-40cdc6292ca1.gif" alt="ko.react.org-header-before" width="300"/>  |  <img src="https://user-images.githubusercontent.com/13115713/197377597-ae0cdb87-9423-4e7c-b966-c4941785fa04.gif" alt="ko.react.org-header-before" width="300"/> |
| As you see, text '자습서' is displayed as below with line-breaks. '자\n습\n서' | As you see, text '자습서' is displayed as it is. |
=> Fix: Line-broken Korean text in header links

src/content/reference/react-dom/components/select.md
원문의 업데이트가 발생했을때 라인넘버를 보면서 확인하는데 원문의 라인 넘버를 그대로 유지하면 문서유지에 도움 됩니다.
기존 영문서랑 같은 라인 넘버를 가지게 됩니다.
=> Change line according to review

src/content/reference/react-dom/components/progress.md
=> Translate: <progress>

src/content/reference/react/PureComponent.md
#637 에서 보고된 CI 오류를 수정합니다.
원인은 PureComponent 문서에서 헤더의 아이디를 설정하는 구문이 한 줄 아래로 내려가 있어서 '아이디가 없는' 헤더가 발생했고 이에 따라 모든 헤더에 아이디가 있도록 설정한 규칙 검사에서 오류가 발생한 것입니다.
Resolves #637
=> FIX: ci-check error

src/content/learn/javascript-in-jsx-with-curly-braces.md
- 초안이 작성되어 있는 문서라 원문과 동일한지 확인했습니다.
- 일부 문장을 자연스럽게 수정했습니다.
=> Translate: JavaScript in JSX with Curly Braces

src/components/Layout/Footer.tsx, src/components/Layout/Page.tsx, src/content/blog/2020/12/21/data-fetching-with-react-server-components.md, src/content/blog/2021/12/17/react-conf-2021-recap.md, src/content/blog/2022/06/15/react-labs-what-we-have-been-working-on-june-2022.md, src/content/blog/2023/03/22/react-labs-what-we-have-been-working-on-march-2023.md, src/content/blog/2023/05/03/react-canaries.md, src/content/blog/index.md, src/sidebarBlog.json
블로그와 관련된 부분들 기존 번역 완료된 페이지와 확인하여 모두 통일해두었습니다.
1. 메인 페이지 하단
- 블로그 프리뷰 기존 제목과 싱크 맞추기
2. 블로그 페이지 (/blog) 
- `<BlogCard />` 제목, 날짜, 내용
- 모두 번역 완료된 기존 페이지 및 인트로와 최대한 동일하게 반영
3. 블로그 포스트
- 포스트 타이틀 아래 `날짜, 작성자` 형식으로 노출되도록 통일
- 포스트 하단 Footer 링크 제목, 번역 완료된 페이지와 싱크 맞추기
4. Footer 와 Survey
|  | screenshot |
|:---:|:---:|
| as-is | <img width="800" alt="as-is" src="https://github.com/reactjs/ko.react.dev/assets/69497936/d3f6846d-f9e5-4fbc-9648-ddd8bafd815b"> |
| to-be | <img width="800" alt="to-be" src="https://github.com/reactjs/ko.react.dev/assets/69497936/4ac2de6b-edfb-4fbd-9fb9-b0faa7dbab9c"> |
=> Translate: sync blog index, footer and preview

src/components/Layout/HomeContent.js, src/content/blog/2022/03/08/react-18-upgrade-guide.md, src/content/reference/react-dom/client/hydrateRoot.md
1. **hydrateRoot.md** 1f518a4f4a3190a4fb422b38004e0f1d1b5db6d1
- 리액트 -> `React`로 수정 
-  cf. [Translate Glossary - 번역하면 안되는 용어](https://github.com/reactjs/ko.react.dev/wiki/Translate-Glossary#%EB%B2%88%EC%97%AD%ED%95%98%EB%A9%B4-%EC%95%88%EB%90%98%EB%8A%94-%EC%9A%A9%EC%96%B4)
- 오번역된 부분 수정
- `use state` -> state를 사용
2. **react-18-upgrade-guide.md** f1867f9d729717403853699cd87f527195ca2d77
- 번역되지 않은 부분 추가 번역
- 번역 후 제거되지 않은 원문 제거
- markdown 적용되도록 수정
| as-is | to-be |
|:---:|:---:|
|  <img width="302" alt="as-is" src="https://github.com/reactjs/ko.react.dev/assets/69497936/51368b63-bb16-4e7a-8d38-b2368caeb50d"> | <img width="302" alt="to-be" src="https://github.com/reactjs/ko.react.dev/assets/69497936/f9c8587f-1447-48fa-b8f3-b72d75669c56">  |
3. **HomeContent.js** …
=> Translate: react-18-upgrade-guide and fix translation in hydrateRoot

src/components/DocsFooter.tsx, src/components/Layout/Feedback.tsx, src/components/MDX/Challenges/Challenge.tsx, src/components/MDX/Challenges/Challenges.tsx, src/components/MDX/ExpandableCallout.tsx, src/components/MDX/ExpandableExample.tsx, src/components/MDX/MDXComponents.tsx, src/components/MDX/Recap.tsx, src/components/Tag.tsx
사이트 내 다양한 컴포넌트에서 사용되는 타이틀, 설명, 버튼명, 태그 등의 번역을 추가하였습니다.
|No.| Desc | Path (src/components) | Screenshot |
|:---|:---|:---|:---|
| 1 | 이전,다음 버튼 | DocsFooter.tsx | <img width="907" alt="이전,다음" src="https://github.com/reactjs/ko.react.dev/assets/69497936/0c63d7a0-a654-4af4-9183-a0b701a37d0a"> |
| 2 | 피드백 | Layout/Feedback.tsx | <img width="791" alt="피드백" src="https://github.com/reactjs/ko.react.dev/assets/69497936/d282ea29-248c-41f9-bf43-84066acef926"> |
| 3 | 챌린지 | MDX/Challenges/Challenge.tsx<br/>MDX/Challenges/Challenges.tsx  | <img width="982" alt="챌린지1" src="https://github.com/reactjs/ko.react.dev/assets/69497936/be2a2195-a334-4e69-80a5-8604d337b428"><br/><img width="987" alt="챌린지2" src="https://github.com/reactjs/ko.react.dev/assets/69497936/ab0f26c4-61b1-4fb0-8ae0-fd9c43d8 …
=> Translate: component titles, descriptions, buttons, tags and more

src/content/reference/react/lazy.md
=> Translate: lazy

src/components/Layout/Footer.tsx, src/content/learn/managing-state.md, src/sidebarHome.json
https://github.com/reactjs/ko.react.dev/issues/738
여기서 나온 이슈를 바탕으로 기존에 있던 단어를 수정합니다
=>  fix: Escape hatches -> 탈출구 #738

src/content/reference/react-dom/components/common.md
onBlur 이벤트 핸들러 함수와 onFocus 이벤트 핸들러 함수의 설명이 동일한 것을 발견하였습니다.
onFocus 이벤트 핸들러 함수 설명에서 번역이 잘못된 부분을 수정했습니다.
=> Fix: translation error for onFocus

src/content/learn/referencing-values-with-refs.md, src/content/reference/react/Fragment.md, src/pages/404.js
공식 문서 내 오타 및 잘못된 하이퍼링크 경로를 수정합니다.
- `Fragment.md` : 문서 내 경로에 불필요한 `()` 제거
- `referencing-values-with-refs` : 100밀리초 -> 10밀리초 ([원문 링크](https://github.com/reactjs/react.dev/blob/main/src/content/learn/referencing-values-with-refs.md#example-building-a-stopwatch-example-building-a-stopwatch))
=> fix : 오타 및 마크다운 문서 내 경로 수정

src/components/Layout/Toc.tsx, src/components/MDX/Sandpack/CustomPreset.tsx, src/components/MDX/Sandpack/DownloadButton.tsx, src/components/MDX/Sandpack/NavigationBar.tsx, src/components/MDX/Sandpack/OpenInCodeSandboxButton.tsx, src/components/MDX/Sandpack/ResetButton.tsx, src/components/MDX/TerminalBlock.tsx, src/utils/prepareMDX.js
`<SandPack>`, `<TerminalBlock>`, TableOfContent 중 아직 번역되지 않은 부분을 번역하였습니다.
번역에 대해 의견 주시면 반영하도록 하겠습니다!
=> Translate: `<SandPack>`, `<TerminalBlock>`, TableOfContent

src/content/reference/react-dom/server/renderToString.md
마크다운 문법 오류로 문서 링크가 깨져 있어 이를 수정하였습니다.
=>  Fix broken file link in the usage of renderToPipeableStream

src/content/learn/reacting-to-input-with-state.md, src/content/learn/render-and-commit.md, src/content/learn/scaling-up-with-reducer-and-context.md
- [렌더링 그리고 커밋](https://ko.react.dev/learn/render-and-commit)
- [State를 사용해 Input 다루기](https://ko.react.dev/learn/reacting-to-input-with-state)
- [tasks 리스트 / task 리스트] 혼용되어 있던 표현을 **tasks 리스트** 로 통일
예제에서 tasks라는 변수에 리스트를 담고 사용되고 있는데요, 변수명 그대로인 복수형이 자연스럽지 않을까 생각했습니다.
---
- 누락된 문단들을 번역 
---
---
---
---
---
=> fix: missing part of reducer

src/content/reference/react-dom/components/common.md
문서 내 오타를 수정했습니다.
- `CompositionE드vent 핸들러` -> `CompositionEvent 핸들러`
=> fix: 오타 수정

src/content/reference/react-dom/components/select.md
- 번역이 누락된 props 부분을 추가했습니다.
- 기존 문서를 가이드라인에 맞춰 수정했습니다.
- 잘못된 번역어를 수정했습니다.
- 문장을 매끄럽게 다듬었습니다.
- 하이퍼링크된 문서에 한글 버전이 있는 경우 한글 버전으로 수정했습니다.
-----
=> fix: Add missing translations

src/content/reference/react/useTransition.md
=> [번역누락]: useTransition페이지의 누락된 번역

src/content/reference/react-dom/preconnect.md
안녕하세요 :) [preconnect 문서](https://ko.react.dev/reference/react-dom/preconnect)를 번역했습니다.
=> Translate: preconnect

src/content/learn/thinking-in-react.md
close #942 
[React로 사고하기](https://ko.react.dev/learn/thinking-in-react) 페이지 내의 누락된 ConsoleBlock 요소를 추가했습니다.
동시에, 기존 번역되어있던 console의 오류 메시지를 원문으로 수정했습니다.
&nbsp;
+++
ConsoleBlock 내부의 문장들은 실제 console에서 보여지는 메시지인데,
번역을 해야할 지 말아야 할 지에 대한 가이드가 없는 것 같습니다.
[한글 번역 예](https://ko.react.dev/reference/react-dom/components/textarea#my-text-area-doesnt-update-when-i-type-into-it)
다른 국가들의 경우에는 번역하고 있지 않습니다.
=> Fix: React로 사고하기 페이지의 ConsoleBlock 누락 수정

src/content/learn/responding-to-events.md
`src/content/learn/responding-to-events.md` 문서 내부의 링크와 오타를 수정하였습니다.
1. 관습적으로 handle로 시작하여 -> 관습적으로 handle로 시작하며
- '여'를 이용한 조사 사용이 어색하여, '여'를 '며'로 변경하였습니다. 
2. 화살표 함수에 대해 더 알아보세요 -> https://ko.javascript.info/arrow-functions-basics
- 영문 공식 문서를 한글 공식 문서 링크로 변경하였습니다.
3.  `<button onClick={handleClick}>` -> https://developer.mozilla.org/ko/docs/Web/HTML/Element/button
- 영문 공식 문서를 한글 공식 문서 링크로 변경하였습니다.
4. 접근성을 위한 마크업 작성법에 대해 더 알아보세요. -> https://developer.mozilla.org/ko/docs/Learn/Accessibility/HTML
- 영문 공식 문서를 한글 공식 문서 링크로 변경하였습니다.
=> fix: link and typo

README.md
`README.md` 문서를 수정하였습니다. 수정한 내용은 크게 아래와 같습니다.
1. reactjs.org -> react.dev
- 과거 reactjs.org 대신, 최신 react.dev로 업데이트 하였습니다.
2. 영문 [README.md](https://github.com/reactjs/react.dev) 문서와 싱크를 맞추었습니다.
3. 잘못된 조사 사용 및 잘못 표기된 마크다운 부분을 수정하였습니다.
4. '문제 해결하기' 파트를 '기여하기' 파트 바로 다음으로 옮겼습니다.
- '문제 해결하기' 부분은 코드 기여와 관련된 파트이기 때문에, '기여하기' 파트 다음에 오는 것이 좀 더 좋은 것 같습니다.
=> fix: README.md typo and synchronize with react.dev

src/content/blog/2023/03/16/introducing-react-dev.md
안녕하세요😄 용어 Tutorial이 textlint 검사에 의해 오류가 발생하여 수정하였습니다.
상세내용은 아래와 같습니다.
1. wiki에 따라 '튜토리얼'을 '자습서'로 변경하였습니다.
2. 마침표 뒤에 불필요한 공백이 있는 경우, 해당 공백을 삭제하였습니다.
=> fix: typo 'Tutorial' linted by textlint

src/content/learn/lifecycle-of-reactive-effects.md, src/content/reference/react-dom/client/hydrateRoot.md, src/content/reference/react/cloneElement.md, src/content/reference/react/createElement.md, src/content/reference/rsc/use-server.md
안녕하세요😁 textlint에 의해 검사된 아래 2개의 키워드를 수정하였습니다.
용어 `term`|정규표현식 `sources`|번역 `target`|논의 `discussions`|
---|---|---|---|
Element|`/Element/`, `/[엘앨]리먼츠/`, `/앨리먼트/`|엘리먼트|[#2](https://github.com/reactjs/ko.react.dev/issues/2)|
Function|`/Function/`, `/Functional/`|함수|[#2](https://github.com/reactjs/ko.react.dev/issues/2)|
특이사항
1. 문맥에 따라, 인라인 코드 블럭을 추가한 경우가 존재합니다.
=> fix: typo 'element' 'function' linted by textlint

src/content/reference/react/Children.md, src/content/reference/react/createElement.md
안녕하세요😁 textlint에 의해 검사된 아래 1개의 키워드를 수정하였습니다.
용어 `term`|정규표현식 `sources`|번역 `target`|논의 `discussions`|
---|---|---|---|
Children|`/Child(?:ren)?/`|자식|[#2](https://github.com/reactjs/ko.react.dev/issues/2)|
특이사항
1. 문맥 상 'children'이 코드의 일부로 차용된 것이라, '자식'으로 번역되기 보다는 인라인 코드 블럭으로 감싸는 것이 옳다 생각됩니다.
이외 수정 사항
1. `엘리먼트` -> `element`: 인라인 코드 블럭 내부는 번역되면 안됩니다. (react.dev 참고하여 수정하였습니다)
1. null -> `null`: 바로 앞 문장의 null은 인라인 코드블럭으로 감싸져 있습니다. 따라서, 해당 null도 코드 블럭으로 감싸져야 합니다.
=> fix: typo 'children' linted by textlint

src/content/learn/updating-objects-in-state.md, src/content/reference/react/useInsertionEffect.md, src/content/reference/react/useLayoutEffect.md
안녕하세요😁 textlint에 의해 검사된 아래 1개의 키워드를 수정하였습니다.
용어 `term`|정규표현식 `sources`|번역 `target`|논의 `discussions`|
---|---|---|---|
Dependency|`/\bDependenc(?:y\|ies)\b/`|의존성|[#841](https://github.com/reactjs/ko.react.dev/issues/841)|
특이 사항
1. 수정 내역 모두 번역을 하기 보다는, 인라인 코드 블럭을 추가하는게 올바른 상황이라, 백틱으로 감쌌습니다.
=> fix: typo 'dependencies' linted by textlint

src/content/learn/you-might-not-need-an-effect.md
>React에서 데이터는 부모 컴포넌트에서 자식 컴포넌트로 흐릅니다.  ...<생략>... 자식과 부모 모두 동일한 데이터가 필요하므로 부모 컴포넌트가 해당 데이터를 가져와서 자식에게 대신 내려주도록 하세요.
>이렇게 하면 데이터가 부모에서 자식으로 내려오기 때문에 데이터 흐름이 더 간단하고 예측 가능하게 유지됩니다.
위의 내용과 영어 원문으로 미루어 볼 때, 부모가 자식에게 데이터를 전달하는 것이므로 자식"에서"가 아닌 자식"에게"가 올바른 번역인 것 같습니다.
그리고 같은 글에서
>Effect에서 부모에게 데이터 전달하기
와 같은 식으로 주석이 작성되어 있어 문장을 그와 같은 방식으로 다듬었습니다.
=> fix: correct mistranslation

src/content/reference/react/useDeferredValue.md
안녕하세요😊 #927 이슈에서 언급된 번역 중복 문제를 해결하였습니다.
기존에 동일하게 번역된 내용이 있어, 영어 원문만 삭제하였습니다.
resolve: #927
=> docs(typo): fix typo in useDeferredValue (#927)

wiki/best-practices-for-translation.md
안녕하세요😊 #918 에서 언급된 깨진 링크를 수정하였습니다. (`wiki/best-practices-for-translation.md`)
이제 모든 링크가 정상 작동합니다.
resolve: #918
=> docs(wiki): fix broken links in best-practices-for-translation (#918)

src/sidebarReference.json
- `/reference` 경로의 사이드바에서 번역되지 않은 메뉴를 번역하였습니다.
=> docs: update `sidebarReference.json`

.github/workflows/analyze.yml
안녕하세요😊 `actions/upload-artifact@v2`가 deprecated 됨에 따라 아래와 같이 오류가 발생하여 버전을 올려서 PR 합니다.
https://github.com/actions/upload-artifact
공식 문서에서는 6월 30일자로 `v2`가 deprecated 되었다고 적혀있습니다.
현재 이슈로 #1044 의 CI가 통과되지 못하고 있습니다.
@hg-pyun
=> build: bump `actions/upload-artifact` from `v2` to `v4`

.github/workflows/textlint_lint.yml, package.json
안녕하세요😊 textlint를 이용한 lint 검증 자동화를 완료하였습니다.
아직 모든 translate glossary가 포함된건 아니지만, 지금까지 70% 정도 진행된 내용을 바탕으로 검증되도록 하였습니다.
변경 내용은 아래와 같습니다.
1. `textlint_lint.yml`
- 파일 이름 및 변수 이름들은 기존 workflows 들과 동일한 컨벤션을 사용하여 명명하였습니다.
- `src` 하위 디렉토리의 마크다운 파일들이 변경되었을 때, textlint 관련 파일들이 변경되었을 때, 현재 워크플로 파일이 변경되었을 때 검사를 진행합니다.
2. `package.json`
- lint-staged에 `yarn textlint-lint` 스크립트를 추가하여, pre-commit 훅에서 자동 검증이 진행되도록 하였습니다.
> [!NOTE]
>
> 현재 PR에서 workflow가 정상 동작합니다.
>
> ![image](https://github.com/user-attachments/assets/b87832ab-32e3-4589-942d-7b3042510aae)
resolve: #926, #971
@hg-pyun
=> ci: lint automation using github workflow `textlint_lint.yml` and `lint-staged` (#926 #971)

.github/workflows/textlint_test.yml
안녕하세요😊 textlint의 자체 test 검증 자동화를 완료하였습니다.
이전 #1048 PR과 유사한 방식으로 진행하였습니다.
다만, `lint-staged`에는 test 관련 내용이 이미 포함되어 있기 때문에 이 부분은 따로 추가하지 않았습니다.
변경 내용은 아래와 같습니다.
1. `textlint_test.yml`
- 파일 이름 및 변수 이름들은 기존 workflows 들과 동일한 컨벤션을 사용하여 명명하였습니다.
- textlint 관련 파일들이 변경되었을 때와 현재 워크플로 파일이 변경되었을 때 검사를 진행합니다.
> [!NOTE]
>
> 현재 PR에서 workflow가 정상 동작합니다.
>
> ![image](https://github.com/user-attachments/assets/b0804a57-a1a2-4030-8c41-d77fa29258c3)
@hg-pyun
=> ci: test automation using github workflow `textlint_test.yml`

src/content/reference/react-dom/components/meta.md
=> Translate: meta (#901)

textlint/data/rules/translateGlossary.js, wiki/translate-glossary.md
안녕하세요😊
textlint를 통한 검사를 진행할 때 사용하던 기존 정규표현식을 더욱 정확하게 동작하도록 업데이트 하였습니다.
수정 내역은 아래와 같습니다.
1. `\b` 기호를 추가하여 단어 간 경계를 더욱 명확하게 하였습니다.
2. 불필요하게 2개 이상의 정규표현식으로 나뉘어 있던 정규표현식들을 하나로 합쳤습니다.
3. `wiki/translateGlossary.md`는 자동으로 업데이트 되었습니다.
=> perf: update regexp in translateGlossary.js

.vscode/settings.json
안녕하세요😊
기존 ko.react.dev 레포지토리는 코드를 수정하고 저장(<kbd>ctrl</kbd> + <kbd>s</kbd> or <kbd>command</kbd> + <kbd>s</kbd>) 등을 눌러도 코드 포매팅이 자동으로 수정되지 않아 불편함을 느꼈습니다.
`.husky`와 `lint-staged`를 통한 pre-commit 훅을 통해 자동 포매팅 수정이 이루어지기는 하지만, 이는 코드 수정이 모두 완료된 커밋 직전에야 진행될 뿐입니다.
따라서, 저장 버튼을 누를 때 마다 코드 포매팅이 수정되면 훨씬 좋을 것 같아 `.vscode/settings.json` 파일을 통해 VScode에서 저장 버튼을 누르면 자동으로 코드 포매팅이 수정되도록 하였습니다.
VScode는 가장 대중적인 에디터라 해당 파일을 추가해두면 많은 사람들이 활용할 수 있을 것 같습니다.
수정 내역은 아래와 같습니다.
1. `"editor.formatOnSave": true,`: 저장 버튼을 누를 때 마다 코드 포매팅이 자동으로 수정됩니다.
1. `"editor.formatOnPaste": true,`: 붙여넣기를 할 때 마다 코드 포매팅이 자동으로 수정됩니다.
1. `"editor.defaultFormatter": "esbenp.prettier-vscode",`: 기본 포매터로 `prettier`를 설정합니다.
1. `"editor.codeActionsOnSave": {"source.fixAll.eslint": "always"}`: 저장 버튼을 누를 때 마다 eslint의 fix 옵션이 자동으로 적용됩니다.
=> feat: create `.vscode/settings.json`

.github/PULL_REQUEST_TEMPLATE.md, README.md, textlint/data/rules/translateGlossary.js, wiki/textlint/what-is-textlint.md
안녕하세요😊
textlint 관련 wiki 문서를 업데이트 하였습니다. 예전에 진작 수정했어야 했는데 이제서야 진행하네요ㅠㅠ🥲
수정 내역은 아래와 같습니다
1. `wiki/textlint/what-is-textlint.md`: textlint 구현 관련 내용들을 모두 추가하였습니다.
2. `README.md`: textlint 관련 문서 링크 추가 및 사소한 오탈자를 수정하였습니다.
3. `textlint/data/rules/translateGlossary.js`: 간단한 주석을 추가하였습니다.
4. `PULL_REQUEST_TEMPLATE`: textlint 관련 문서 링크 추가 및 사소한 오탈자를 수정하였습니다.
=> docs: update wiki/textlint/what-is-textlint.md

src/content/reference/react/index.md
안녕하세요😊
레퍼런스 페이지의 사이드바에 적힌 내용과 싱크가 맞도록 페이지 내용을 수정하였습니다.
=> docs(typo): fix typo in reference/react/index.md

src/content/reference/react/Suspense.md
안녕하세요😊
[Suspense](https://ko.react.dev/reference/react/Suspense) 문서를 읽다가 오타들이 있어 수정합니다.
주요 수정 내역은 아래와 같습니다.
1. 조사 사용이 어색한 부분을 수정하였습니다.
2. 글에서 나오는 영단어들은 React 혹은 컴퓨터 과학의 고유 명사인 경우가 대다수라, 첫 글자를 모두 대문자로 표기하였습니다.
3. 인라인 코드 블럭 내부의 컴포넌트 이름들은 번역되면 안되는데 번역되어서 수정하였습니다.
=> docs(typo): fix typo in Suspense.md

src/content/learn/managing-state.md, src/content/learn/referencing-values-with-refs.md, src/content/learn/reusing-logic-with-custom-hooks.md
안녕하세요,
textlint 검사 과정에서 누락된 'escape hatches' -> '탈출구' 를 올바르게 번역하였습니다.
=> docs(typo): fix typo escape hatches linted by textlint

src/content/learn/extracting-state-logic-into-a-reducer.md
안녕하세요😊
`extracting-state-logic-into-a-reducer.md` 문서를 읽다 맞춤법이 애매한 부분들 수정하였습니다.
추가로, 방향 있는 따옴표들을 단방향 따옴표로 바꿔서 문서 간 따옴표 방향이 올바르게 표시되도록 하였습니다.
=> docs(typo): fix typos in `extracting-state-logic-into-a-reducer.md`

src/content/reference/react/use.md
안녕하세요😊
`use.md` 문서를 읽다가 맞춤법, 가독성이 떨어지는 문장, 번역이 잘못된 부분 등을 **영어 원문 기준**으로 수정하였습니다.
=> docs: update `use.md`

src/content/learn/scaling-up-with-reducer-and-context.md
안녕하세요😊
`scailing-up-with-reducer-and-context.md` 문서를 읽다가 맞춤법 및 인라인 코드 블럭으로 감싸지지 않은 텍스트 등을 수정하였습니다.
=> docs: update `scailing-up-with-reducer-and-context.md`

src/content/learn/keeping-components-pure.md
안녕하세요,
[컴포넌트 순수하게 유지하기](https://ko.react.dev/learn/keeping-components-pure) 페이지에 오탈자가 존재하여 수정하는 작업을 진행하였습니다.
'새로운 요리를 만들 수 있습니다다.' -> '새로운 요리를 만들 수 있습니다.'
=> docs(typo): update `keeping-components-pure.md`

src/content/reference/react/cache.md
안녕하세요!
`cache.md` 를 읽어보다 변수명의 경우 원문으로 표현 됐을 때 더 자연스러운 느낌이 들어서 수정했습니다.
=> docs: fix typo in cache.md

src/content/reference/react/cache.md
안녕하세요!
`cache.md` 를 읽어보다 Markdown이 제대로 표시되지 않는 부분이 있어서 수정했습니다.
=> docs: fix markdown in `cache.md`

src/content/learn/synchronizing-with-effects.md
=> Fix missing translate

src/content/community/team.md
안녕하세요! 자기소개를 한국어로 반역해 보려고 했어요. 아직 한국어로
잘 못해서 실수한 게 있으면 고치주세요~
=> docs: Translate my bio to Korean

src/content/reference/react/useImperativeHandle.md
`useImperativeHandle.md`의 번역이 되지 않은 부분을 일부 수정했습니다.
=> docs: update useImperativeHandle.md

src/content/reference/react/Suspense.md
- 기울임체 적용되지 않은 문자 기울임체로 수정
- \*중단(Suspend)*로 표기된 문자 <em>중단(Suspend)</em>로 수정
- 한,영 중복된 내용 제거
- 어색한 표현 수정
- use 사용해서 Promise 값 읽기 -> use 사용해서 캐시된 Promise 값 읽기
- **F**allback으로 표기된 부분 **f**allback으로 수정
=> docs: update `Suspense.md`

src/content/reference/react/useEffect.md
- https://github.com/reactjs/ko.react.dev/issues/1122
- 번역 빠진 문구 수정 및 영문 제거
=> docs: update useEffect.md

src/content/learn/updating-arrays-in-state.md
안녕하세요! [배열 State 업데이트하기](https://ko.react.dev/learn/updating-arrays-in-state#adding-to-an-array) 페이지의 _배열에 항목 추가하기_ 부분에서 클릭 이벤트 내 `setName('');` 코드를 제거했습니다.
새로운 배열로 추가했을 때와 동일하게 작동해서 확인해보니, set 함수를 통해 리렌더링을 시켜주고 있었습니다. 원문과 동일하게 `setName('');` 코드 부분을 제거하였습니다!
- https://react.dev/learn/updating-arrays-in-state#adding-to-an-array
=> docs: remove unnecessary state reset in List component

src/content/reference/react/useReducer.md
#1129 
- 번역 되지 않은 부분 번역 추가했습니다.
=> docs: useReducer caveats untranslated partial translation

src/content/reference/react/useRef.md
- forwardRef에 대한 설명은 React19이후엔 필요없어지고 영문 문서에도 해당 내용이 빠져 뺐습니다.
- 단순 ref를 props로 넘겨준다는 미번역된 문구 번역했습니다.
- 콘솔 에러메시지가 나타나지 않았고 영문 문서와 동일한 콘솔 에러메시지를 표시하도록했습니다. (기존엔 에러메시지가 보이지 않았네요.)
=> docs: remove ref guide about react18

src/content/reference/react/cache.md, src/content/reference/rsc/directives.md, src/content/reference/rsc/server-components.md, src/content/reference/rsc/server-functions.md, src/content/reference/rsc/use-client.md, src/content/reference/rsc/use-server.md
Close #1141
- 다음 페이지 내 RSC 블록 내 컨텐츠를 번역했습니다.
- [캐시](https://ko.react.dev/reference/react/cache)
- [지시어](https://ko.react.dev/reference/rsc/directives)
- [서버 컴포넌트](https://ko.react.dev/reference/rsc/server-components)
- [use client](https://ko.react.dev/reference/rsc/use-client)
- [use server](https://ko.react.dev/reference/rsc/use-server)
- [server function](https://ko.react.dev/reference/rsc/server-functions)
=> docs: translate content in RSC block

src/content/reference/react/startTransition.md
[startTransition](https://ko.react.dev/reference/react/startTransition) 문서에 누락된 번역사항이 있어 수정하였습니다.
[useTransition](https://react.dev/reference/react/useTransition#starttransition-parameters) 문서에 동일한 문장이 있어, 기존 번역과 동일하게 수정하였습니다.
=> docs: fix missing translation in `startTransition`

src/content/reference/react-dom/client/createRoot.md
[createRoot 페이지 매개변수 부분](https://ko.react.dev/reference/react-dom/client/createRoot#parameters)을 번역하였습니다.
before
- <img width="937" alt="image" src="https://github.com/user-attachments/assets/0871e7f5-ec27-4264-a1f0-cb43cf0aa903" />
after
- <img width="934" alt="image" src="https://github.com/user-attachments/assets/442a2f50-380e-42bf-b936-228d370a4005" />
=> docs: Translate the parameter section of the createRoot page

src/content/learn/render-and-commit.md
[렌더링 그리고 커밋](https://ko.react.dev/learn/render-and-commit) 페이지에서 번역되지 않고 남은 영어 원문을 삭제합니다.
=> docs(content): remove redundant English explanation on React rendering

src/content/reference/react/legacy.md
close #1167 
**Legacy api 페이지 번역**
- Legacy apis 섹션의 forwardRef 번역
- Removed apis 섹션 번역
=> docs: Legacy React apis 페이지 번역

src/content/learn/installation.md
다음 페이지를 번역했습니다.
[처음부터 React 앱 만들기](https://ko.react.dev/learn/installation)
=> docs: update content/learn/installtion.md

src/content/learn/tutorial-tic-tac-toe.md
안녕하세요. 틱택토 게임에 있는 영어 문구를 번역하려다 위의 한글로 번역되어 있는 사항이라 제거 작업 진행했습니다!
=> docs: update content/learn/tutorial-tic-tac-toe.md

src/content/learn/creating-a-react-app.md
=> docs: update `creating-a-react-app.md`

src/content/learn/setup.md
다음 페이지를 번역하였습니다.
[설정하기](https://ko.react.dev/learn/setup)
=> docs: translate setup in react-learn

src/content/learn/manipulating-the-dom-with-refs.md
리액트 공식문서 Ref로 DOM조작하기 요약부분에 번역 안된 영문을 한글로 번역하였습니다.
페이지 링크(https://ko.react.dev/learn/manipulating-the-dom-with-refs)
=> docs: translate Recap in manipulating-the-dom-with-refs

src/content/learn/passing-data-deeply-with-context.md
다음 페이지를 번역하였습니다.
또한, 이미 번역되었음에도 계속 남아있던 영어 원문을 제거하였습니다.
페이지 링크(https://ko.react.dev/learn/passing-data-deeply-with-context)
=> docs: translate passing-data-deeply-with-context in react-learn

src/content/learn/state-a-components-memory.md
번역된 내용에서 영어 원문을 참고하여 보완하고 영어 원문은 제거했습니다.
=> docs: update content/learn/state-a-components-memory.md

src/content/reference/react/useTransition.md
잘못된 번역 내용이 있어 수정했어요.
```
When clicking multiple times, it’s possible for previous requests to finish after later requests.
```
```
- 여러 번 클릭하면 먼저 보낸 요청이 나중에 보낸 요청보다 먼저 처리될 수 있습니다.
+ 여러 번 클릭하면 먼저 보낸 요청이 나중에 보낸 요청보다 늦게 처리될 수 있습니다.
```
=> docs: fix typo in useTransition.md

src/content/learn/removing-effect-dependencies.md
오타가 있어서 수정했습니다.
**수정 전:**
> 로직을 두 개의 Effect로 분할하고, 각 Effect는 동기화해야 하는 props즈에 반응합니다.
**수정 후:**
> 로직을 두 개의 Effect로 분할하고, 각 Effect는 동기화해야 하는 props에 반응합니다.
=> docs: fix typo in removing-effect-dependencies.md

src/content/reference/react/useActionState.md
useActionState 섹션의 번역 문서에서 중복된 영어 원문(항목 4~6) 을 제거했습니다.
항목 1, 2, 3에서 이미 한국어로 번역된 설명이 충분히 제공되고 있음에도 불구하고, 바로 아래에 영어 원문(항목 4, 5, 6)이 다시 나열되어 있어 독자의 혼란을 유발할 수 있습니다.
해당 중복 내용은 문서의 가독성을 떨어뜨리고, 다른 번역 문서들과 스타일의 일관성도 맞지 않습니다.
React 공식 문서의 번역 지침에서도 중복 없이 자연스러운 번역 제공을 권장하고 있습니다.
- React 공식 문서 useActionState 섹션 PR 부분
따라서, 해당 내용 수정을 통해 문서의 명료성을 향상 시키고 독자의 혼란을 방지하여 전체 번역 문서의 스타일 및 품질 개선을 기대합니다.
`useActionState` 훅에 대한 번역을 최신 영어 원문에 맞춰 업데이트하고, 표현을 보다 자연스럽고 명확하게 다듬었습니다.
기존 번역은 기본적인 의미 전달에는 문제가 없었지만, 일부 문장이 다소 부자연스럽고 기술적인 뉘앙스가 정확하지 않은 부분이 있었습니다.
또한, 최신 React 공식 문서 영문 내용을 기준으로 정확한 의미 전달과 문체 개선이 필요하다고 판단하여 수정했습니다.
[React 영문 docs](https://react.dev/reference/react/useActionState)
감사합니다.
=> docs: remove duplicated English content and improve translation clarity in useActionState docs

src/content/reference/react-dom/preinit.md, src/content/reference/react/useActionState.md
이 PR은 React 공식 문서 중 [preinit API 영문 공식문서](https://react.dev/reference/react-dom/preinit)를 한국어로 번역한 내용을 포함합니다.
원문의 구조와 형식을 그대로 유지하며 자연스러운 한국어로 번역했습니다. 또한, 용어는 기존 번역 스타일과 일관되게 사용하였습니다.
링크, 코드 예제, 주석 등은 원문을 빠짐없이 충실히 반영했습니다.
감사합니다.
=> docs: translate preinit reference page into Korean

src/content/reference/react/useActionState.md
- 한국어 번역 내용 아래 혼란이 되는 영어 원문 (항목 4, 5, 6) 삭제
- `useActionState` 관련 문서의 기존 번역을 원문에 더 충실하게 다듬었습니다.
- 함수 시그니처, 상태 흐름, 액션 함수의 인자 전달 방식 등을 보다 명확하고 자연스럽게 표현했습니다.
- 반복적 표현을 줄이고, 문서 스타일에 맞게 문장을 정돈했습니다.
- React 영문 공식 문서의 내용에서 빠진 내용들을 모두 번역하였습니다.
- 항목 1, 2, 3에서 이미 한국어로 번역된 설명이 충분히 제공되고 있음에도 불구하고, 바로 아래에 영어 원문(항목 4, 5, 6)이 다시 나열되어 있어 독자의 혼란을 유발할 수 있습니다. 
- 기존 번역은 의미 전달은 되고 있었으나, 문장 구조가 원문과 다소 괴리되어 있거나 축약 표현으로 인해 글을 읽을 때 오해의 소지가 있었습니다.  따라서 초심자나 번역만 보고 학습하는 독자를 고려해 더 직관적이고 정확하게 전달되도록 개선했습니다.
- React 공식 문서와 비교했을 때 빠진 내용들이 있었습니다. 따라서, 빠진 내용들도 번역을 하여 모두 내용에 담았습니다.
- [React 영문 문서](https://react.dev/reference/react/useActionState)
- [현재 React 한글 문서](https://ko.react.dev/reference/react/useActionState#usage)
=> docs: improve and complete Korean translation of useActionState documentation

src/content/blog/2024/12/05/react-19.md, src/content/blog/index.md, src/content/learn/escape-hatches.md, src/content/learn/lifecycle-of-reactive-effects.md, src/content/learn/referencing-values-with-refs.md, src/content/learn/removing-effect-dependencies.md, src/content/learn/you-might-not-need-an-effect.md
=> docs: fix typos

src/components/Layout/TopNav/TopNav.tsx
안녕하세요. React 18 아이콘에서 예상치 못한 호버 이펙트가 발생해서 수정 코드 제안드립니다.
해당 문제는 svg width, height이 아주 크게 잡혀있어서 발생했습니다.
```javascript
const react18Icon = (
<svg
stroke="currentColor"
fill="none"
strokeWidth="2"
viewBox="0 0 24 24"
strokeLinecap="round"
strokeLinejoin="round"
height="200px" <- 문제 발생 지점
width="200px" <- 문제 발생 지점
xmlns="http://www.w3.org/2000/svg">
<path d="M8 8h1v8"></path>
<path d="M15 12h-1a1 1 0 0 1 -1 -1v-2a1 1 0 0 1 1 -1h2a1 1 0 0 1 1 1v2a1 1 0 0 1 -1 1zh-1a1 1 0 0 0 -1 1v2a1 1 0 0 0 1 1h2a1 1 0 0 0 1 -1v-2a1 1 0 0 0 -1 -1"></path>
</svg>
);
```
<br />
<br />
<br />
아마도 이렇게 작성된 것은 다른 svg와 같은 크기인 28로 잡았을 때 react18Icon이 너무 작아서 크게 설정한 것 같습니다.
따라서 svg 속성인 width, height을 직접 변경하지 않고 해당 버튼에 overflow-hidden을 추가해서 문제 해결하는 것이 어떤지 여쭤봅니다!
<div style="display: flex;">
</div>
<br />
<br />
<br />
수정 …
=> Fix unexpected header hover effect on react18Icon

src/content/learn/lifecycle-of-reactive-effects.md
lifecycle-of-reactive-effects.md 내용 중, 링크에 괄호가 들어가 참조가 깨진 문제를 수정했습니다.
=> docs: remove duplicate parentheses in learn link

src/content/learn/you-might-not-need-an-effect.md
아래 문단을 보면 `_이유_는` 이라고 적힌 부분이 있는데 이는 렌더링 되어 보여질 때 `<em>이유</em>는` 으로 보여지는 것이 아닌, `_이유_는` 처럼 렌더링 되어 보여집니다.
https://github.com/reactjs/ko.react.dev/blob/cf4724852a111dd33d92858591b5805cdc25d2e5/src/content/learn/you-might-not-need-an-effect.md?plain=1#L338
이는 CommonMark 스펙을 보았을 때 이어지는 단어 중간에 들어가는 경우 `*`을 사용해야만 강조가 적용되도록 제한되어 있는 것으로 보였습니다, <https://spec.commonmark.org/0.31.2/#emphasis-and-strong-emphasis>:
Many implementations have also restricted intraword emphasis to the * forms, to avoid unwanted emphasis in words containing internal underscores. (It is best practice to put these in code spans, but users often do not.)
그래서 `*이유*는` 꼴로 변경하는 것도 고려했으나 1) 개인적인 느낌에서 한글을 기울여 쓸 경우 옆 단어를 침범하여 보기 좋지 않다는 느낌이 있고[^1], 2) 다른 부분에서 의도적으로 띄어쓰는 방향으로 작성한 것으로 보이는 부분이 있어 `_이유_ 는` 꼴로 바꾸는 PR을 만들어 올립니다. …
=> docs: fix markdown syntax typo in you-might-not-need-an-effect.md

src/content/learn/referencing-values-with-refs.md
[Ref와 State의 차이#자세히 살펴보기: useRef는 내부적으로 어떻게 동작하나요?](https://ko.react.dev/learn/referencing-values-with-refs#differences-between-refs-and-state) 부분을 아래와 같이 수정했습니다. 이때, 독자 입장에서 더 읽기 편하게 하는 데 중점을 두었습니다.
```
- 이 예시에서는 State Setter가 어떻게 사용되지 않는지 주의하세요.
+ 이 예시에서는 State Setter를 사용하지 않는 점에 주목하세요.
```
[원문](https://react.dev/learn/referencing-values-with-refs#differences-between-refs-and-state)에는 'Note how the state setter is unused in this example.'라고 표현합니다. 코드와 설명의 앞뒤 맥락을 보면, 'useRef는 항상 동일한 객체를 반환해야 하므로 state setter가 필요하지 않다.'라는 것을 전달하려는 목적으로 보입니다. 따라서 'how'를 '어떻게'로 직역하는 대신, state setter를 사용하지 않는 '현상' 자체에 대한 뉘앙스가 담기게 의역해보았습니다. 더불어, 이런 뉘앙스에는 '주의'보다는 '주목'이 의미 전달에 더 적합하다고 판단했습니다. (* [note 뜻 - 네이버 사전](https://en.dict.naver.com/#/entry/enko/775deb835c894f519a6912a545c24f64))
=> docs: improve sentences for more natural phrasing

src/content/learn/referencing-values-with-refs.md
'챌린지 4 of 4: 최신 state 읽기' 中 정답보기 클릭 시 보이는 해설이 원문과 일치하지 않는 부분이 있어 수정했습니다.
```md
- current 텍스트는 렌더링에도 사용되므로, 이 예에서는 state 변수(렌더링을 위한) 둘 다와 ref(시간 초과 시 읽음)가 필요합니다.
+ current 텍스트는 렌더링에도 사용되므로, 이 예에서는 state 변수(렌더링을 위한)와 ref(시간 초과 시 읽음) 둘 다 필요합니다.
```
* 원문
https://react.dev/learn/referencing-values-with-refs#challenges
* 번역
https://ko.react.dev/learn/referencing-values-with-refs#challenges
=> docs: fix typo in referencing-values-with-refs.md

src/content/learn/manipulating-the-dom-with-refs.md
'Ref로 DOM 조작하기' 페이지의 [챌린지 4 of 4: 별개의 컴포넌트에서 검색 필드에 포커스 이동하기](https://ko.react.dev/learn/manipulating-the-dom-with-refs#challenges) 내 '힌트 보기' 클릭 시 표시되는 설명을 수정했습니다. 해당 부분에 오래된 설명(한국어)과 원문의 최신 설명(영어)이 공존하는 것으로 보입니다. 
※ [React 19 버전 이후, forwardRef는 deprecated됨](https://ko.react.dev/reference/react/forwardRef)
오래된 설명(한국어)을 제외하고 원문의 최신 설명(영어)을 적절히 번역하여, 다음과 같이 수정할 것을 제안합니다.
```
- `SearchInput`같은 컴포넌트에서 `forwardRef`를 사용해서 DOM 노드를 노출할 필요가 있습니다.
+ `SearchInput` 같은 컴포넌트에서 DOM 노드를 노출하려면 `ref`를 prop 처럼 전달해야 합니다.
```
=> docs: add a missing translation

src/content/reference/react/useEffect.md
=> docs: fix typo in useEffect.md

src/content/reference/react/ViewTransition.md
[ViewTranstion API](https://ko.react.dev/reference/react/ViewTransition)의 콘텐츠를 한국어로 번역했습니다.
close #1226
=> docs: add Korean translation for `<ViewTransition>` API page

src/content/reference/react/Activity.md
[Activity API](https://ko.react.dev/reference/react/Activity)의 콘텐츠를 한국어로 번역했습니다.
close #1229
=> docs: add Korean translation for <Activity> API page

src/content/reference/react/useId.md, src/content/reference/react/useLayoutEffect.md
두 개의 레퍼런스 문서에서 번역되지 않은 영어 문장들을 한국어로 번역했습니다.
- "useId currently cannot be used in async Server Components" 
→ "useId는 현재 비동기 서버 컴포넌트에서 사용할 수 없습니다"
- "You do not need to pass identifierPrefix if you only have one React app on the page" 
→ "페이지에 React 앱이 하나만 있는 경우에는 identifierPrefix를 전달할 필요가 없습니다"
- "If you trigger a state update inside useLayoutEffect, React will execute all remaining Effects immediately including useEffect" 
→ "useLayoutEffect 내부에서 state 업데이트를 실행하면 React는 useEffect를 포함한 나머지 모든 Effect를 즉시 실행합니다"
=> docs: Translate remaining English sentences in useId.md and useLayoutEffect.md to Korean

src/content/reference/react/StrictMode.md
Strict Mode 개발 전용 동작 설명 부분에서 번역되지 않은 영어 문장을 한국어로 번역했습니다.
**변경된 내용:**
- "Your components will re-run refs callbacks an extra time to find bugs caused by missing ref cleanup."
→ "컴포넌트가 ref 클린업이 누락되어 발생한 버그를 찾기 위해 ref를 다시 실행합니다."
**변경 이유:**
- 해당 항목만 영어로 남아있어 문서의 일관성이 떨어짐
- 다른 항목들과 동일한 번역 스타일로 통일하여 가독성 향상
=> docs: translate missing ref callback line in Strict Mode section

src/components/Layout/HomeContent.js
수정내용
* `HomeContent` 소제목에 "네이티브" 를 추가합니다
* AS-IS: `웹 및 사용자 인터페이스를 위한 라이브러리`
* TO-BE: `웹 및 네이티브 사용자 인터페이스를 위한 라이브러리`
설명
* `react.dev` `HomeContent` 소제목은 `The library for web and native user interfaces` 입니다.
* `ko.react.dev` 은 `웹 및 사용자 인터페이스를 위한 라이브러리` 로, 원문의 `native` 부분이 누락되었습니다.
=> chore: add "네이티브" in `HomeContent` subtitle

src/content/reference/react/StrictMode.md
React 19 공식 문서의 StrictMode 섹션에서 부분 활성화 시 프로덕션 동작에 대한 설명을 한국어로 번역했습니다.
- StrictMode에서 누락된 번역 부분 한국어 번역
- 기존 한국어 문서 스타일과 일관성 유지
=> Translate strictmode production behavior explanation to korean

src/content/reference/react-dom/client/createRoot.md
createMode 페이지 내 Error logging in production 섹션에 대한 번역을 진행했습니다.
- 원문 링크: https://ko.react.dev/reference/react-dom/client/createRoot#error-logging-in-production
- 관련 이슈: #1251
=> docs: translate 'Error logging in production' section in createMode page

src/content/reference/react-dom/static/prerenderToNodeStream.md
원문 링크: https://ko.react.dev/reference/react-dom/static/prerenderToNodeStream
해당 이슈: #1263 
해당 오타를 수정하였습니다.
=> docs: fixprerenderToNode.md

src/content/reference/react/useDeferredValue.md
원문 링크 : https://ko.react.dev/reference/react/useDeferredValue
해당 이슈:  #1266 
- 구버전 한글 번역을 삭제하고, 최신 영문 내용에 맞춰 수정했습니다.
- 변경된 링크 : [Next.js] 링크를 최신 문서 경로`(https://nextjs.org/docs/app/getting-started/fetching-data#with-suspense)`로 업데이트했습니다.
=> docs: translate useDeferredValue.md

src/content/reference/react/useState.md
다음 페이지를 번역했습니다.
[useState](https://ko.react.dev/reference/react/useState)
=> docs: update content/reference/react/useState.md

src/content/reference/react-dom/client/createRoot.md, src/content/reference/react/useDeferredValue.md
- 링크 : https://ko.react.dev/reference/react-dom/client/createRoot
- 이슈 : https://github.com/reactjs/ko.react.dev/issues/1260
- 변경사항 미리보기
=> docs: translate createRoot.md

src/content/blog/2025/04/23/react-labs-view-transitions-activity-and-more.md
이슈 번호 : #1308 
1. Customizing animations 번역
블로그 > [React Labs: View Transitions, Activity, and more](https://ko.react.dev/blog/2025/04/23/react-labs-view-transitions-activity-and-more#customizing-animations)
2. Shared Element Transitions 번역
블로그 > [React Labs: View Transitions, Activity, and more](https://ko.react.dev/blog/2025/04/23/react-labs-view-transitions-activity-and-more#shared-element-transitions)
=> docs: translate Customizing animations and Shared Element Transitions

src/content/reference/react-dom/server/renderToString.md
이슈 링크 : #1284 
Migrating from renderToString to a static prerender on the server 섹션에 대한 번역을 진행하였습니다.
=> docs: translate 'Migrating from renderToString to a static prerender on the server' 

src/content/reference/react/createContext.md
이슈번호 : #1327 
다음 세 부분의 번역부분을 손봤습니다. 번역 모범사례를 참고하여 그대로 번역하기보단 보다 자연스럽다고 생각되는 문장으로 의역했습니다. 예를들어 문제해결 파트의 'I can't find~' 부분을 찾을 수 없다라기 보단 모르겠다 등으로... 그리고 provider 소제목 같은 경우(50번째 줄) '.provider'가 사용되지 않는 맥락이더라도 미관상 전체 문장을 백틱으로 감싸는게 좋을것 같아서 소소하게 맺음백틱 위치를 수정했습니다.
- 반환값
- somecontext provider의 '중요합니다' part
- 문제해결
=> docs: createContext 미세한 번역 추가
